// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c,a,b){var e=jQuery;var d=e("ul",b);var f={position:"absolute",left:0,top:0,width:"100%",height:"100%"};this.go=function(g,h){var i=e(a.get(g)).clone().css(f).hide().appendTo(b);if(!c.noCross){var j=e(a.get(h)).clone().css(f).appendTo(b);d.hide();j.fadeOut(c.duration,function(){j.remove()})}i.fadeIn(c.duration,function(){d.css({left:-g+"00%"}).show();i.remove()});return g}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"",next:"",duration:20*100,delay:42*100,width:800,height:600,autoPlay:true,stopOnHover:false,loop:false,bullets:0,caption:true,captionEffect:"slide",controls:true,logo:"engine1/loading.gif",onBeforeStep:0,images:[{src:"./dsc_0056.jpg",title:"NTHJC Year End Show",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0110.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0130.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0135.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0087.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0091.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0070.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0100.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0103.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0117.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0126.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0065.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0118.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0119.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0121.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0107.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0063.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0134.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"},{src:"./dsc_0136.jpg",title:"",href:"http://www.bridlewoodequestrian.com/YESlider"}]});