// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c,a,b){var e=jQuery;var d=e("ul",b);var f={position:"absolute",left:0,top:0,width:"100%",height:"100%"};this.go=function(g,h){var i=e(a.get(g)).clone().css(f).hide().appendTo(b);if(!c.noCross){var j=e(a.get(h)).clone().css(f).appendTo(b);d.hide();j.fadeOut(c.duration,function(){j.remove()})}i.fadeIn(c.duration,function(){d.css({left:-g+"00%"}).show();i.remove()});return g}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"",next:"",duration:20*100,delay:42*100,width:640,height:480,autoPlay:true,stopOnHover:false,loop:false,bullets:0,caption:true,captionEffect:"slide",controls:true,logo:"engine1/loading.gif",onBeforeStep:0,images:[{src:"./dsc_0248.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun13.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun14.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun15.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./dsc_0131.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun17.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun18.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun19.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun6.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./fun7.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./img_0290.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./img_0282.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./img_0293.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./img_0277.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"},{src:"./dsc_0133.jpg",title:"",href:"http://www.bridlewoodequestrian.com/FunSlider"}]});